title: "Your Name"
description: "A short tagline or bio"
url: "https://aminizadyar.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
