title: "Amin Izadyar"
description: "PhD Finance"
url: "https://aminizadyar.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

author:
  name:  ""
  avatar: "/assets/images/avatar.jpg"
  bio:   ""


# Tell Jekyll to output files in _pages
collections:
  pages:
    output: true

# Give everything in that collection the page layout by default
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

