title: "Amin Izadyar"
description: "PhD Finance"
url: "https://aminizadyar.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
