title: "Amin Izadyar"
description: "PhD Finance"
url: "https://aminizadyar.github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

author:
  name:  "Amin Izadyar"
  avatar: "/assets/images/avatar.jpg"
  bio:   "Developer, tinkerer, and tea enthusiast."

