name: Build and Deploy Pages

# Trigger on pushes to main
on:
  push:
    branches:
      - main   # or 'master' if that's your default

# Give the workflow permission to write the Pages branch
permissions:
  contents: read    # for checkout
  pages: write      # for deploy
  id-token: write   # required by actions/configure-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
